let weightM=14;
let heightM=5;
let AgeM=7;
let weightG=10;
let heightG=9;
let AgeG=5;
let Age=5
let weight=6.25
let height=10
exports.HM=heightM;
exports.WM=weightM;
exports.AM=AgeM;
exports.HG=heightG;
exports.WG=weightG;
exports.AG=AgeG;
exports.H=height;
exports.W=weight;
exports.A=Age;
